### ISSUE TITLE
Add ability to create a different orders for import and require statements

### ISSUE THREAD

**Issue by smlkA** [snak1t/vscode-imports-organization#12]
![issue](https://user-images.githubusercontent.com/31129837/86401090-58e7ac80-bcb2-11ea-91f7-c164dd6252b4.png)

It would be nice to config plugin to avoid import and require statements mixing. 
For example I would like to have only import statements first and then all require calls. 
I think it would be very useful for persons who use certain eslint (see attached screenshot).

**Comment by snak1t** [comment]
added an option mixType, could be set as mixed or es_to_top
