### ISSUE TITLE
Add support for commonjs modules as ExpressionStatement

### ISSUE THREAD

**Issue by snak1t** [snak1t/vscode-imports-organization#4]
`require('package').useApp();`

**Comment by snak1t** [comment]
For CommonJSModule add static method `isExpressionStatement(statement: Statement): boolean`

add branching logic for methods `getSourceName`, `is`, 'makeNode`

**Comment by smlkA** [comment]
If you do not mind, I will take that issue

**Comment by snak1t** [comment]
Sure, could you also make sure that following cases are covered?
```
require('package-a').method();
require('package-b').member.method();
require('package-c').member.member; // don't know why someone needs this, but still
```

**Comment by snak1t** [comment]
done in #9
